import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import StyleDictionary from "style-dictionary";

const root = process.cwd();
const tokensDir = path.join(root, "src", "design-system", "tokens");
const outputFile = path.join(root, "src", "design-system", "styles", "generated.css");
const checkOnly = process.argv.includes("--check");
const coreComponents = [
  "button.tsx",
  "card.tsx",
  "input.tsx",
  "textarea.tsx",
  "badge.tsx",
  "dialog.tsx",
  "tabs.tsx",
  "tooltip.tsx",
];

const files = {
  primitive: "primitive.json",
  base: "semantic.base.json",
  light: "semantic.light.json",
  dark: "semantic.dark.json",
  oled: "semantic.oled.json",
  comfortable: "density.comfortable.json",
  compact: "density.compact.json",
  component: "component.json",
};

const readJson = async (file) =>
  JSON.parse(await fs.readFile(path.join(tokensDir, file), "utf8"));

const isToken = (value) =>
  value && typeof value === "object" && Object.hasOwn(value, "$value");

function collectTokens(node, inheritedType, tokenPath = [], result = []) {
  if (!node || typeof node !== "object") return result;
  const currentType = node.$type ?? inheritedType;

  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith("$")) continue;
    const nextPath = [...tokenPath, key];

    if (isToken(value)) {
      const type = value.$type ?? currentType;
      if (!type) throw new Error(`Token ${nextPath.join(".")} is missing $type`);
      if (!value.$description) {
        throw new Error(`Token ${nextPath.join(".")} is missing $description`);
      }
      result.push({
        path: nextPath,
        name: nextPath.join("-"),
        value: value.$value,
        type,
      });
    } else {
      collectTokens(value, currentType, nextPath, result);
    }
  }

  return result;
}

const aliasPattern = /^\{([^}]+)\}$/;

function validateAliases(tokens, availableTokens) {
  const tokenMap = new Map(tokens.map((token) => [token.path.join("."), token]));
  const availableMap = new Map(
    availableTokens.map((token) => [token.path.join("."), token]),
  );

  function visit(token, chain = []) {
    if (typeof token.value !== "string") return;
    const match = token.value.match(aliasPattern);
    if (!match) return;

    const targetName = match[1];
    if (chain.includes(targetName)) {
      throw new Error(`Circular token reference: ${[...chain, targetName].join(" -> ")}`);
    }

    const target = tokenMap.get(targetName) ?? availableMap.get(targetName);
    if (!target) {
      throw new Error(
        `Token ${token.path.join(".")} references missing token ${targetName}`,
      );
    }
    visit(target, [...chain, token.path.join(".")]);
  }

  tokens.forEach((token) => visit(token));
}

const variableValue = (value) => {
  if (typeof value !== "string") return String(value);
  const match = value.match(aliasPattern);
  return match ? `var(--${match[1].replaceAll(".", "-")})` : value;
};

function cssBlock(selector, tokens) {
  const declarations = tokens
    .map((token) => `  --${token.name}: ${variableValue(token.value)};`)
    .join("\n");
  return `${selector} {\n${declarations}\n}`;
}

const sources = Object.fromEntries(
  await Promise.all(
    Object.entries(files).map(async ([key, file]) => [key, await readJson(file)]),
  ),
);

const primitiveTokens = collectTokens(sources.primitive);
const semanticBaseTokens = collectTokens(sources.base);
const lightTokens = collectTokens(sources.light);
const darkTokens = collectTokens(sources.dark);
const oledTokens = collectTokens(sources.oled);
const comfortableTokens = collectTokens(sources.comfortable);
const compactTokens = collectTokens(sources.compact);
const componentTokens = collectTokens(sources.component);
const baseTokens = [...primitiveTokens, ...semanticBaseTokens, ...lightTokens];

for (const tokens of [
  lightTokens,
  semanticBaseTokens,
  darkTokens,
  oledTokens,
  comfortableTokens,
  compactTokens,
  componentTokens,
]) {
  validateAliases(tokens, baseTokens);
}

// Initialize Style Dictionary for DTCG parsing and alias resolution validation.
for (const source of [
  [files.primitive],
  [files.primitive, files.base],
  [files.primitive, files.light],
  [files.primitive, files.dark],
  [files.primitive, files.oled],
  [files.primitive, files.light, files.component],
]) {
  const dictionary = new StyleDictionary({
    source: source.map((file) => path.join(tokensDir, file)),
    usesDtcg: true,
    log: { verbosity: "silent" },
  });
  await dictionary.hasInitialized;
}

const output =
  [
  "/* Generated by scripts/build-tokens.mjs. Do not edit directly. */",
  cssBlock(":root", primitiveTokens),
  cssBlock(":root", semanticBaseTokens),
  cssBlock(':root, [data-theme="light"]', lightTokens),
  cssBlock('[data-theme="dark"]', darkTokens),
  cssBlock('[data-theme="oled"]', oledTokens),
  cssBlock(":root, [data-density=\"comfortable\"]", comfortableTokens),
  cssBlock('[data-density="compact"]', compactTokens),
  cssBlock(":root", componentTokens),
  ].join("\n\n") + "\n";

if (checkOnly) {
  const current = await fs.readFile(outputFile, "utf8").catch(() => "");
  if (current !== output) {
    throw new Error("Generated token CSS is stale. Run `pnpm tokens:build`.");
  }

  const primitiveVariablePattern =
    /var\(--(?:color|space|size|radius|font|duration|easing|breakpoint|container)-/;
  const literalColorPattern =
    /(?:#[0-9a-f]{3,8}\b|(?:rgb|hsl|oklch|lab|lch|color)\()/i;

  for (const component of coreComponents) {
    const componentPath = path.join(root, "src", "components", "ui", component);
    const source = await fs.readFile(componentPath, "utf8");
    if (primitiveVariablePattern.test(source)) {
      throw new Error(`${component} consumes a primitive CSS variable directly.`);
    }
    if (literalColorPattern.test(source)) {
      throw new Error(`${component} contains a literal color.`);
    }
  }
} else {
  await fs.mkdir(path.dirname(outputFile), { recursive: true });
  await fs.writeFile(outputFile, output, "utf8");
}

console.log(
  `Validated ${[
    ...primitiveTokens,
    ...semanticBaseTokens,
    ...lightTokens,
    ...darkTokens,
    ...oledTokens,
    ...comfortableTokens,
    ...compactTokens,
    ...componentTokens,
  ].length} DTCG tokens${checkOnly ? "" : " and generated CSS"}.`,
);
